version: "3.3"
services:
  redis:
    image: redis:alpine
    container_name: boilerplate-redis

  mariadb:
    image: mariadb:latest
    container_name: boilerplate-mariadb
    working_dir: /app
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=boilerplate
      - MYSQL_DATABASE=boilerplate
      - MYSQL_USER=boilerplate
      - MYSQL_PASSWORD=boilerplate
    ports:
      - "8003:3306"

  webserver:
    image: nginx:alpine
    container_name: boilerplate-webserver
    working_dir: /app
    volumes:
      - .:/app
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  app:
    build: phpdocker/php-fpm
    container_name: boilerplate-app
    working_dir: /app
    volumes:
      - .:/app
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini